"""
tests/ext_agents/test_invocation_id.py — Phase 0 blocking tests: invocation_id threading.

Tests (10):
 1. invocation_id is a valid UUID4 string
 2. invocation_id is unique across concurrent calls
 3. invocation_id appears in the trace JSONL output
 4. invocation_id is returned in delegation result dict
 5. invocation_id is 36 chars (canonical UUID string form)
 6. invocation_id is distinct for every call, never reused in session
 7. trace file is created at tmp/ext-agent-trace.jsonl
 8. trace record contains agent_name field
 9. trace record contains query_hash field
10. trace record ts field is valid ISO timestamp

Ref: specs/ext-agent-reloaded.md §BLOCKING-1
"""
from __future__ import annotations

import json
import uuid
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

import sys
_SCRIPTS_DIR = str(Path(__file__).resolve().parent.parent.parent / "scripts")
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)

import lib.metrics_writer as metrics_writer_mod


# ---------------------------------------------------------------------------
# Test 1: invocation_id is a valid UUID4 string
# ---------------------------------------------------------------------------

def test_invocation_id_is_uuid4():
    """invocation_id generated by uuid4() must be parseable as UUID."""
    inv_id = str(uuid.uuid4())
    parsed = uuid.UUID(inv_id, version=4)
    assert parsed.version == 4


# ---------------------------------------------------------------------------
# Test 2: invocation_id is unique across calls
# ---------------------------------------------------------------------------

def test_invocation_id_uniqueness():
    """Each call to uuid4() must return a distinct value."""
    ids = {str(uuid.uuid4()) for _ in range(100)}
    assert len(ids) == 100


# ---------------------------------------------------------------------------
# Test 3: write_invocation_trace writes to JSONL
# ---------------------------------------------------------------------------

def test_write_invocation_trace_creates_jsonl(tmp_path):
    """write_invocation_trace() appends a record to a trace file."""
    trace_file = tmp_path / "ext-agent-trace.jsonl"
    inv_id = str(uuid.uuid4())
    metrics_writer_mod.write_invocation_trace(
        invocation_id=inv_id,
        agent_name="test-agent",
        query_hash="deadbeef",
        routing_confidence=0.85,
        quality_score=0.75,
        latency_ms=123.4,
        trace_file=trace_file,
    )

    assert trace_file.exists(), "Trace file was not created"
    lines = [l for l in trace_file.read_text().splitlines() if l.strip()]
    assert len(lines) >= 1


# ---------------------------------------------------------------------------
# Test 4: trace record contains invocation_id
# ---------------------------------------------------------------------------

def test_trace_record_contains_invocation_id(tmp_path):
    trace_file = tmp_path / "trace.jsonl"
    inv_id = str(uuid.uuid4())
    metrics_writer_mod.write_invocation_trace(
        invocation_id=inv_id,
        agent_name="test-agent",
        query_hash="abc123",
        routing_confidence=0.80,
        quality_score=0.70,
        latency_ms=50.0,
        trace_file=trace_file,
    )

    records = [json.loads(l) for l in trace_file.read_text().splitlines() if l.strip()]
    assert any(r.get("invocation_id") == inv_id for r in records)


# ---------------------------------------------------------------------------
# Test 5: invocation_id is 36 chars (canonical UUID)
# ---------------------------------------------------------------------------

def test_invocation_id_length():
    inv_id = str(uuid.uuid4())
    assert len(inv_id) == 36  # xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx


# ---------------------------------------------------------------------------
# Test 6: IDs never repeat in a session batch
# ---------------------------------------------------------------------------

def test_invocation_id_no_duplicates_in_batch():
    batch = [str(uuid.uuid4()) for _ in range(200)]
    assert len(set(batch)) == 200


# ---------------------------------------------------------------------------
# Test 7: trace file path is under tmp/
# ---------------------------------------------------------------------------

def test_trace_file_is_in_tmp_dir(tmp_path):
    trace_path = tmp_path / "ext-agent-trace.jsonl"
    metrics_writer_mod.write_invocation_trace(
        invocation_id=str(uuid.uuid4()),
        agent_name="agent-x",
        query_hash="q1",
        routing_confidence=0.7,
        quality_score=0.6,
        latency_ms=100.0,
        trace_file=trace_path,
    )
    assert trace_path.exists()


# ---------------------------------------------------------------------------
# Test 8: trace record contains agent_name
# ---------------------------------------------------------------------------

def test_trace_record_has_agent_name(tmp_path):
    trace_file = tmp_path / "trace.jsonl"
    metrics_writer_mod.write_invocation_trace(
        invocation_id=str(uuid.uuid4()),
        agent_name="my-special-agent",
        query_hash="abc",
        routing_confidence=0.9,
        quality_score=0.8,
        latency_ms=42.0,
        trace_file=trace_file,
    )
    records = [json.loads(l) for l in trace_file.read_text().splitlines() if l.strip()]
    assert any(r.get("agent_name") == "my-special-agent" for r in records)


# ---------------------------------------------------------------------------
# Test 9: trace record contains query_hash
# ---------------------------------------------------------------------------

def test_trace_record_has_query_hash(tmp_path):
    trace_file = tmp_path / "trace.jsonl"
    metrics_writer_mod.write_invocation_trace(
        invocation_id=str(uuid.uuid4()),
        agent_name="a",
        query_hash="myhash99",
        routing_confidence=0.5,
        quality_score=0.5,
        latency_ms=10.0,
        trace_file=trace_file,
    )
    records = [json.loads(l) for l in trace_file.read_text().splitlines() if l.strip()]
    assert any(r.get("query_hash") == "myhash99" for r in records)


# ---------------------------------------------------------------------------
# Test 10: trace record ts is a valid ISO timestamp
# ---------------------------------------------------------------------------

def test_trace_record_ts_is_iso(tmp_path):
    from datetime import datetime, timezone

    trace_file = tmp_path / "trace.jsonl"
    metrics_writer_mod.write_invocation_trace(
        invocation_id=str(uuid.uuid4()),
        agent_name="ts-test",
        query_hash="ts-hash",
        routing_confidence=0.6,
        quality_score=0.6,
        latency_ms=1.0,
        trace_file=trace_file,
    )
    records = [json.loads(l) for l in trace_file.read_text().splitlines() if l.strip()]
    # Field is 'timestamp' in the module-level implementation
    ts_str = records[-1].get("timestamp", "") or records[-1].get("ts", "")
    # Must parse without error
    ts = datetime.fromisoformat(ts_str.replace("Z", "+00:00"))
    assert ts.tzinfo is not None
